trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_STORAGE_ACCOUNT_KEY: $(azureStorageAccountKey)

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            displayName: 'Build React App'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'build'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
          - script: |
              echo "Listing contents of artifact staging directory"
              ls -R $(Build.ArtifactStagingDirectory)
            displayName: 'List Build Artifact Contents'

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'adityanewconnection'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Cleaning up existing files in the \$web container..."
                az storage blob delete-batch --account-name adityapstorage --account-key $(AZURE_STORAGE_ACCOUNT_KEY) --source '$web'

                echo "Uploading new build files to \$web container..."
                az storage blob upload-batch --account-name adityapstorage --account-key $(AZURE_STORAGE_ACCOUNT_KEY) --source $(Build.ArtifactStagingDirectory)/drop --destination '$web'
            displayName: 'Deploy to Azure Storage'
