trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            displayName: 'Build React App'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'build'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(AZURE_SUBSCRIPTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az storage blob upload-batch --account-name $(AZURE_STORAGE_ACCOUNT_NAME) --auth-mode key -d '$web' -s $(Build.ArtifactStagingDirectory)/drop
            displayName: 'Upload to Blob Storage'

          - script: |
              az logout
            displayName: 'Logout'
