trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            displayName: 'Build React App'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'build'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'adityanewconnection'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az storage blob delete-batch --account-name adityapstorage --source '$web'
                az storage blob upload-batch --account-name adityapstorage --source $(Pipeline.Workspace)/drop --destination '$web'
            displayName: 'Deploy to Azure Storage'
