trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            displayName: 'Build React App'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'build'
              ArtifactName: 'drop'
            displayName: 'Publish Build Artifacts'

  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: Deploy
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureFileCopy@4
            inputs:
              SourcePath: '$(System.DefaultWorkingDirectory)/drop'
              azureSubscription: 'Pay-As-You-Go'
              Destination: 'AzureBlob'
              storage: 'adityapstorage'
              ContainerName: '$web'

