trigger:
  branches:
    include:
      - main

stages:
- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'specific'
        project: 'Tiwari-Cloud'  # Replace with your project name if not the current project
        definition: 'imapsingh007.AdityaReact'  # Replace with your build pipeline name
        buildId: $(Build.BuildId)
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)/drop'

    - task: AzureFileCopy@4
      inputs:
        SourcePath: '$(System.ArtifactsDirectory)/drop'
        azureSubscription: 'Pay-As-You-Go'  # Replace with your Azure subscription name
        Destination: 'AzureBlob'
        storage: 'adityapstorage'  # Replace with your Storage Account name
        ContainerName: '$web'
        cleanTargetFolder: true
