trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            displayName: 'Build React App'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'build'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
          - script: |
              echo "Listing contents of artifact staging directory"
              ls -R $(Build.ArtifactStagingDirectory)
            displayName: 'List Artifact Staging Directory Contents'

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'adityanewconnection'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                SOURCE_DIR="$(Build.ArtifactStagingDirectory)/drop"
                if [ -d "$SOURCE_DIR" ]; then
                  echo "Uploading files from $SOURCE_DIR to Blob Storage"
                  az storage blob upload-batch --account-name $(AZURE_STORAGE_ACCOUNT_NAME) --auth-mode key -d '$web' -s "$SOURCE_DIR"
                else
                  echo "Error: Source directory $SOURCE_DIR does not exist."
                  exit 1
                fi
            displayName: 'Upload to Blob Storage'

          - script: |
              az logout
            displayName: 'Logout'
